"""add embedding column

Revision ID: 46e3bab3a488
Revises: 83bb296564d6
Create Date: 2025-04-16 09:15:17.787725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46e3bab3a488'
down_revision: Union[str, None] = '83bb296564d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_id', table_name='articles')
    op.drop_table('articles')
    op.drop_table('processed_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_articles',
    sa.Column('article_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cleaned_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='processed_articles_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', name='processed_articles_pkey')
    )
    op.create_table('articles',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pub_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='articles_pkey'),
    sa.UniqueConstraint('link', name='articles_link_key')
    )
    op.create_index('ix_articles_id', 'articles', ['id'], unique=False)
    # ### end Alembic commands ###
