"""created like table

Revision ID: bd938445583d
Revises: 7bc44e97fcbe
Create Date: 2025-06-01 23:25:55.853928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd938445583d'
down_revision: Union[str, None] = '7bc44e97fcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('article_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_liked', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
